### ISSUE TITLE
Include Admin Console dashboard

### ISSUE THREAD

**Issue by kerkhofsd** [xenit-eu/alfresco-health-processor#21]

**Comment by kerkhofsd** [comment]
The Alfresco enterprise dashboards use JMX to persist / overwrite properties. This is not available in ACE (Alfresco Community Edition) and therefore there is no straight forward approach. 

After my initial research and investigation, I think there are a few approaches we can take:

- Introduce a dependency on the Order Of The Bee Support Tools. This module offers persistent subsystem configuration: https://github.com/OrderOfTheBee/ootbee-support-tools/wiki/Persistent-Subsystem-Configuration
- Make the Health Processor dashboard AEE only
- Investigate other alternatives, like persisting and retrieving the state using the `AttributeService`. 
- ... other?

@thijslemmens WDYT?

**Comment by thijslemmens** [comment]
- You could have an optional dependency on OOTB Support Tools. No dashboard without OOTB Support tools.
- AEE is not a real option in my opinion.

Do you plan to overwrite config using the Dashboard?

**Comment by kerkhofsd** [comment]
That was my idea, yes. 

IMO the main requirement here is that it should be possible to make changes in the HealthProcessor subsystem (e.g. enable or disable a HealthProcessorPlugin, adapt the txn range of the IndexingStrategy, ...) and make sure the changes are taken into account, without having to restart Alfresco.
